apiVersion: v1
kind: Service
metadata:
  name: jwt-to-rbac
  labels:
    app: jwt-to-rbac
spec:
  type: ClusterIP
  sessionAffinity: None
  ports:
  - name: jwttorbac
    port: 5555
    targetPort: 5555
  selector:
    app: jwt-to-rbac
